### ISSUE TITLE
Dark Theme - White is slightly too dark

### ISSUE THREAD

**Issue by rohitjmathew** [bkhanale/blog#2]
I would suggest using a little more lighter white to be able to get the user to clearly read and distinguish the text.

**Comment by bkhanale** [comment]
Agree, the dark mode was just an experiment, the color scheme is random at best. I might need to dig a bit deeper and check contrast rules. Can use @a11yproject or something similar for that.

**Comment by rohitjmathew** [comment]
Yeah. I think it's just a few smaller changes. There is a bunch of documentation in [Material Design](https://material.io/design/color/dark-theme.html#properties) guidelines for Dark Theme.

**Comment by bkhanale** [comment]
Closed via https://github.com/bkhanale/bkhanale.github.io/pull/2
